version: "3.7"
services:
  image-sys-api:
    container_name: image-sys-api
    image: image-sys-api-ac:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.profiles.active=dev
      - spring.config.name=image-sys-api-ac
    ports:
      - "8081:8080"
      - "8006:9000"
