spring:
  datasource:
    url: jdbc:mysql://DOMAIN:3306/DATABASE
    username: USERNAME
    password: PASSWORD
    driver-class-name: com.mysql.jdbc.Driver
  main:
    banner-mode: off
  application:
    name: ${project.artifactId}
camel:
  springboot:
    name: ${project.artifactId}
    use-mdc-logging: true
  rest:
    port: 9000
    context-path: /api
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health:
      enabled: true
      show-components: always
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes,metrics,hawtio,jolokia
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
hawito:
  authenticationEnables: false
endpoints:
  jolokia:
    sensitive: false
